# -*- coding: utf-8 -*-
"""machineLearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GfXYszW8cUpxjEion33897kSR5KjgR7o
"""

import torch

"""```
# This is formatted as code
```
[*] Trabajando con adornos
"""

torch.__version__

tensor_a = torch.ones(2,2) # aqui imprimimos tensores de dimension 2x2 así como se 
# coloca
tensor_a

tensor_b = torch.Tensor(2,2)
tensor_b

"""el tensor (tensor_b = torch.Tensor(2,2))
Me devuelve valores aleatorios
"""

tensor_b.uniform_(0,1)

"""Cuando usamos el método uniform_(value, another_value)
estos me devuelven valores aleatorios entre esos números
"""

