# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5pImbSiMN0XLQ4rtPsocQXiTVsJ6KDN
"""

from urllib.request import urlopen
from urllib.error import HTTPError
from bs4 import BeautifulSoup

