# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pfW0VFS9H7G0ha_U5EhtWGwXCbmt8Q2d
"""

from urllib.request import urlopen
from urllib.error import HTTPError
from bs4 import BeautifulSoup

"""installing BeautifulSoup
# pip3 install beautifulsoup4
"""

def get_title(url):

  try:
    html = urlopen(url)
  except HTTPError as e:
    return None


  try:
    bs_obj = BeautifulSoup(html.read())
    title = bs_obj.body.h1
  except AttributeError as e:
    return None
  return title

url = 'http://www.pythonscraping.com/exercises/exercise1.html'
title = get_title(url)

if (title is None):
  print("title could not be found")
else:
  print(title)

