# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pfW0VFS9H7G0ha_U5EhtWGwXCbmt8Q2d
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup

"""installing BeautifulSoup
# pip3 install beautifulsoup4
"""

page_1 = 'http://pythonscraping.com/pages/page1.html'
page_2 = "http://www.pythonscraping.com/exercises/exercise1.html"
#html = urlopen(page_2)

#bs_obj = BeautifulSoup(html.read())
#bs_obj
html = urlopen("http://www.pythonscraping.com/exercises/exercise1.html")
#print(html.read())

try:
  html = urlopen("http://www.pythonscraping.com/exercises/exercise1.html")
  
except HTTPError as e:
  print("Error by: ", str(e))
else:
  if html is None:
    print("url is not founded")
  else:
    print(html.read())
  # program must to be continued without problems