# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15PzfZndB4Qv7piEmeXdCCn6lpaNNeCGp
"""

import torch
import numpy as np
import pandas as pd
from urllib.request import urlopen
from pprint import pprint
import requests

"""key from https://www.weatherbit.io/account/dashboard

**Latitud y longitud de la hacienda especialcorp -2.335017, -80.229759**
"""

key_1 = 'c96c2aa02b1b43e184580f8efe648f59' # weatherbit.io
key_2 = 'ba199bd058f45b1a54e0d25ba95d1ca9' # openweathermap.org
urls = 'http://history.openweathermap.org/data/2.5/history/city?q=London,UK&appid=ba199bd058f45b1a54e0d25ba95d1ca9&units=metric'

time_1 = '1443657600'
time_2 = '1454198400'

res = urlopen('')