# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5pImbSiMN0XLQ4rtPsocQXiTVsJ6KDN
"""

from urllib.request import urlopen
from urllib.error import HTTPError
from bs4 import BeautifulSoup
import re

url = 'http://www.pythonscraping.com/pages/warandpeace.html'
html = urlopen(url)

bs_obj = BeautifulSoup(html)
#bs_obj




# this one is for search any atribute from the css class like
# span and class btn btn-success if you use Bootstrap
name_list = bs_obj.findAll('span', {'class':'green'})

for name in name_list:
  print(name.get_text())


"""
This is the output if you run this process =>

for name in name_list:
  print(name, ": ", name.get_text())

<span class="green">Anna
Pavlovna Scherer</span> :  Anna
Pavlovna Scherer
<span class="green">Empress Marya
Fedorovna</span> :  Empress Marya
Fedorovna
<span class="green">Prince Vasili Kuragin</span> :  Prince Vasili Kuragin
<span class="green">Anna Pavlovna</span> :  Anna Pavlovna
<span class="green">St. Petersburg</span> :  St. Petersburg
<span class="green">the prince</span> :  the prince
<span class="green">Anna Pavlovna</span> :  Anna Pavlovna
<span class="green">Anna Pavlovna</span> :  Anna Pavlovna
<span class="green">the prince</span> :  the prince
<span class="green">the prince</span> :  the prince
<span class="green">the prince</span> :  the prince
<span class="green">Prince Vasili</span> :  Prince Vasili
<span class="green">Anna Pavlovna</span> :  Anna Pavlovna
<span class="green">Anna Pavlovna</span> :  Anna Pavlovna
<span class="green">the prince</span> :  the prince
<span class="green">Wintzingerode</span> :  Wintzingerode
<span class="green">King of Prussia</span> :  King of Prussia
<span class="green">le Vicomte de Mortemart</span> :  le Vicomte de Mortemart
<span class="green">Montmorencys</span> :  Montmorencys
<span class="green">Rohans</span> :  Rohans
<span class="green">Abbe Morio</span> :  Abbe Morio
<span class="green">the Emperor</span> :  the Emperor
<span class="green">the prince</span> :  the prince
<span class="green">Prince Vasili</span> :  Prince Vasili
<span class="green">Dowager Empress Marya Fedorovna</span> :  Dowager Empress Marya Fedorovna
<span class="green">the baron</span> :  the baron
<span class="green">Anna Pavlovna</span> :  Anna Pavlovna
<span class="green">the Empress</span> :  the Empress
<span class="green">the Empress</span> :  the Empress
<span class="green">Anna Pavlovna's</span> :  Anna Pavlovna's
<span class="green">Her Majesty</span> :  Her Majesty
<span class="green">Baron
Funke</span> :  Baron
Funke
<span class="green">The prince</span> :  The prince
<span class="green">Anna
Pavlovna</span> :  Anna
Pavlovna
<span class="green">the Empress</span> :  the Empress
<span class="green">The prince</span> :  The prince
<span class="green">Anatole</span> :  Anatole
<span class="green">the prince</span> :  the prince
<span class="green">The prince</span> :  The prince
<span class="green">Anna
Pavlovna</span> :  Anna
Pavlovna
<span class="green">Anna Pavlovna</span> :  Anna Pavlovna


"""

"""name_list = bs_obj.findAll(text='the prince')
print(len(name_list))
print(name_list)"""


""" 
findAll(tag, attributes, recursive, text, limit, keywords)
find(tag, attributes, recursive, text, keywords)
"""

#all_text =  bs_obj.findAll(id = "text")
#print(all_text[0].get_text())

#bs_obj.findAll('', {'id':'text'})
#bs_obj

#bs_obj.findAll(class_ = "green")

# http://www.pythonscraping.com/pages/page3.html

url_to_open = 'http://www.pythonscraping.com/pages/page3.html'

html = urlopen(url_to_open)

bs_obj = BeautifulSoup(html)

# created a loop to access to any children descendants from 
# the tags

"""
for child in bs_obj.find("table",{"id":"giftList"}).children:
  print(child)
"""

"""for child in bs_obj.find("table",{"id":"giftList"}).tr.next_siblings:
  print(child)"""

new_url = 'http://www.pythonscraping.com/pages/page3.html'
html = urlopen(new_url)
bs_obj = BeautifulSoup(html)

print(bs_obj.find('img', {'src':'../img/gifts/img1.jpg'}).parent.previous_sibling.get_text())

url = 'http://www.pythonscraping.com/pages/page3.html'
html = urlopen(url)
bs_obj = BeautifulSoup(html)

images = bs_obj.findAll('img', {'src': re.compile('\.\.\/img\/gifts/img.*\.jpg')})

for image in images:
  print(image['src'])