# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SmEYuV5eu0quRtfmlv0GmXY1FFzOOZBp
"""

import torch
import numpy as np
import pandas as pd

url_name = "https://covid19.who.int/WHO-COVID-19-global-data.csv"
dataframe = pd.read_csv(url_name)
dataframe

dataframe.columns

# set tha columns to be evaluated

subset = dataframe[[' Country',' New_cases', ' New_deaths']]
subset

columns = subset.columns
columns

cases = torch.tensor(subset.values).float()
cases.shape, cases.type()

mean = torch.mean(cases, dim=0)
mean

std = torch.std(cases, dim=0)
std

target = cases[:,0]
target, target.shape

good = cases[torch.eq(target, 'Ecuador')]
good