# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n906B2p00lk6Vb46paSpN4FYI_2-28nS
"""

import torch
import pandas as pd

class Analysis:
    
    def __init__(self):

        self.url_name = "https://covid19.who.int/WHO-COVID-19-global-data.csv"
        self.dataframe = pd.read_csv(self.url_name)
        self.country_subset = self.dataframe[' Country']
        
        # variables to be called after the class is instantiated 
        self.country_data = ""
        self.target = ""
        self.new_deaths_data = ""

        

    def load(self):
        
        return self.dataframe

    def get_country_stats(self, country):

        self.country_data =  self.dataframe[self.country_subset == country]
        


    def get_new_cases(self):

        return [self.country_subset] 

    def get_mean_(self):

        self.target = torch.tensor( self.country_data[['New_cases']].values).float()
        
        
        mean_data = torch.mean(self.target, dim= 0)
        std_data = torch.std(self.target, dim= 0)

        return mean_data, std_data #self.country_data[[' New_cases']]

    def get_new_deaths(self):
        
        self.new_deaths_data = torch.tensor(self.country_data[['New_deaths']].values).float()
        mean_deaths = torch.mean(self.new_deaths_data, dim = 0)
        std_deaths = torch.std(self.new_deaths_data, dim = 0)

        return mean_deaths, std_deaths

if __name__ == "__main__":
    

    # country to test
    # country = "Ecuador"
    # First instance
    analisis = Analysis()
    analisis.get_country_stats("Ecuador")
    #print(analisis.dataframe)
    #print(analisis.get_country_stats("Ecuador"))
    #print("country_data: ", analisis.country_data)
    print(analisis.country_subset)

    mean_value, std_value = analisis.get_mean_()
    new_columns = ['New_cases']

    mean_value.type()
    print("El promedio de los casos acumulados en Ecuador es: ",int(mean_value.item()))
    print("La desviación estándar es: ", int(std_value.item()))


    print("========================================================================\n")
    
    deaths_mean, deaths_std = analisis.get_new_deaths()
    print("el promedio de las muertes o sea F en el chat: ",int(deaths_mean.item()))
    print("la desviación de las muertes en Ecuador: ", int(deaths_std.item()))



    print("""
    
            La taza de mortalidad en el país está dada por: Muertes
                                                            -------
                                                            Casos totales
    
    """)

    print("=> ", ((int(deaths_mean.item())/int(mean_value.item())))*100, " %" )
