# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n906B2p00lk6Vb46paSpN4FYI_2-28nS
"""

import torch
import pandas as pd

class Analysis:
    
    def __init__(self):

        self.url_name = "https://covid19.who.int/WHO-COVID-19-global-data.csv"
        self.dataframe = pd.read_csv(self.url_name)
        self.country_subset = self.dataframe[' Country']
        
        # variables to be called after the class is instantiated 
        self.country_data = ""
        self.target = ""

        

    def load(self):
        
        return self.dataframe

    def get_country_stats(self, country):

        self.country_data =  self.dataframe[self.country_subset == country]
        


    def get_new_cases(self):

        return [self.country_subset] 

    def get_mean_(self):

        self.target = torch.tensor( self.country_data[[' New_cases']].values).float()
        
        mean_data = torch.mean(self.target, dim= 0)
        std_data = torch.std(self.target, dim= 0)

        return mean_data, std_data #self.country_data[[' New_cases']]

    def get_std_(self, country):
        pass

if __name__ == "__main__":
    

    # country to test
    # country = "Ecuador"
    # First instance
    analisis = Analysis()
    analisis.get_country_stats("Ecuador")
    #print(analisis.dataframe)
    #print(analisis.get_country_stats("Ecuador"))
    #print("country_data: ", analisis.country_data)


    mean_value, std_value = analisis.get_mean_()
    #print("MEAN: ",mean_value)
    





    #print("STD: ", std_value)
    #print(analisis.coutry_data)
    #print(analisis.load())
    #print(analisis.new_cases)

    #print()
    mean_value[0]
    print(analisis.country_data.columns)

mean_value
new_columns = [' New_cases']

mean_value.type()
mean_value.item()
# type(mean_value)